// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PappaETStats.Server.Data;

#nullable disable

namespace PappaETStats.Server.Migrations
{
    [DbContext(typeof(StatsDbContext))]
    [Migration("20261010100319_OksiiStatsAndMatchSeries")]
    partial class OksiiStatsAndMatchSeries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PappaETStats.Server.Domain.LastReadyUp", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long>("CountdownAtUnix")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerGuid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long>("ReadyAtUnix")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.HasIndex("PlayerGuid");

                    b.ToTable("LastReadyUps");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DemoFileName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DemoUploadedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DemoZipFileName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DemoZippedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalMatchId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("MapNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("char(36)");

                    b.Property<int>("SeriesTeam1Faction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("ServerId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerPort")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceMatchId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Winner")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExternalMatchId")
                        .IsUnique();

                    b.HasIndex("SeriesId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchObituary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AttackerGuid")
                        .HasColumnType("varchar(64)");

                    b.Property<int>("AttackerRespawnTime")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MatchRoundId")
                        .HasColumnType("char(36)");

                    b.Property<int>("MeansOfDeath")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetGuid")
                        .HasColumnType("varchar(64)");

                    b.Property<long>("TimestampMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VictimRespawnTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchRoundId");

                    b.HasIndex("TargetGuid");

                    b.HasIndex("TargetGuid", "AttackerGuid");

                    b.ToTable("MatchObituaries");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double?>("AliveSeconds")
                        .HasColumnType("double");

                    b.Property<int?>("Assists")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientNum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DamageGiven")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DamageReceived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("longtext");

                    b.Property<double?>("DistanceMeters")
                        .HasColumnType("double");

                    b.Property<double?>("DownedSeconds")
                        .HasColumnType("double");

                    b.Property<double?>("EngagedSeconds")
                        .HasColumnType("double");

                    b.Property<int>("Gibs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatchSideId")
                        .HasColumnType("char(36)");

                    b.Property<int>("MultiKills2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MultiKills3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MultiKills4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MultiKills5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MultiKills6")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ObjectivesDefused")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ObjectivesDestroyed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ObjectivesPlanted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ObjectivesRepaired")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ObjectivesReturned")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ObjectivesSecured")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rounds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelfKills")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpawnCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Team")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamDamageGiven")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamDamageReceived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamGibs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamKills")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TimePlayedPercent")
                        .HasColumnType("REAL");

                    b.Property<int>("Xp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchSideId");

                    b.ToTable("MatchPlayers");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchPlayerClassStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MatchPlayerId")
                        .HasColumnType("char(36)");

                    b.Property<long>("Ms")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchPlayerId");

                    b.ToTable("MatchPlayerClassStats");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchPlayerWeaponStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Atts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Deaths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Headshots")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hits")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kills")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MatchPlayerId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Weapon")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchPlayerId");

                    b.ToTable("MatchPlayerWeaponStats");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("DefenderTeam")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IngestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NextTimeLimit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("longtext");

                    b.Property<string>("RawJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("RoundEndMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RoundEndUnix")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RoundStartMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RoundStartUnix")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcePayloadJson")
                        .HasColumnType("longtext");

                    b.Property<string>("StatsSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("legacy");

                    b.Property<string>("TimeLimit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("WinnerTeam")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "RoundNumber")
                        .IsUnique();

                    b.ToTable("MatchRounds");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<long?>("EndedAtUnix")
                        .HasColumnType("bigint");

                    b.Property<long>("LastPlayedAtUnix")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<long>("StartedAtUnix")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ServerKey", "LastPlayedAtUnix");

                    b.ToTable("MatchSeries");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchSide", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDefender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MatchRoundId")
                        .HasColumnType("char(36)");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Team")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalDamageGiven")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalDamageReceived")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalGibs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalSelfKills")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalTeamDamageGiven")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalTeamDamageReceived")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalTeamGibs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalTeamKills")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalXp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchRoundId");

                    b.ToTable("MatchSides");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.Player", b =>
                {
                    b.Property<string>("Guid")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("DiscordId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<double>("Mu")
                        .HasColumnType("REAL");

                    b.Property<double?>("MuLarge")
                        .HasColumnType("REAL");

                    b.Property<double?>("MuSmall")
                        .HasColumnType("REAL");

                    b.Property<double>("Sigma")
                        .HasColumnType("REAL");

                    b.Property<double?>("SigmaLarge")
                        .HasColumnType("REAL");

                    b.Property<double?>("SigmaSmall")
                        .HasColumnType("REAL");

                    b.HasKey("Guid");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.PlayerRegistrationToken", b =>
                {
                    b.Property<Guid>("Token")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("DiscordUsername")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsedByEtGuid")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Token");

                    b.HasIndex("DiscordId");

                    b.ToTable("PlayerRegistrationTokens");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.RosterSnapshot", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ServerIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerPort")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("TimestampUnix")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("RosterSnapshots");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.RoundEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long>("LevelTime")
                        .HasColumnType("bigint");

                    b.Property<Guid>("MatchRoundId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnixTimeMs")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Label");

                    b.HasIndex("MatchRoundId", "Sequence")
                        .IsUnique();

                    b.ToTable("RoundEvents");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.Match", b =>
                {
                    b.HasOne("PappaETStats.Server.Domain.MatchSeries", "Series")
                        .WithMany("Maps")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Series");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchObituary", b =>
                {
                    b.HasOne("PappaETStats.Server.Domain.MatchRound", "MatchRound")
                        .WithMany("Obituaries")
                        .HasForeignKey("MatchRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchRound");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchPlayer", b =>
                {
                    b.HasOne("PappaETStats.Server.Domain.MatchSide", "MatchSide")
                        .WithMany("Players")
                        .HasForeignKey("MatchSideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchSide");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchPlayerClassStat", b =>
                {
                    b.HasOne("PappaETStats.Server.Domain.MatchPlayer", "MatchPlayer")
                        .WithMany("ClassStats")
                        .HasForeignKey("MatchPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchPlayer");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchPlayerWeaponStat", b =>
                {
                    b.HasOne("PappaETStats.Server.Domain.MatchPlayer", "MatchPlayer")
                        .WithMany("WeaponStats")
                        .HasForeignKey("MatchPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchPlayer");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchRound", b =>
                {
                    b.HasOne("PappaETStats.Server.Domain.Match", "Match")
                        .WithMany("Rounds")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchSide", b =>
                {
                    b.HasOne("PappaETStats.Server.Domain.MatchRound", "MatchRound")
                        .WithMany("Sides")
                        .HasForeignKey("MatchRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchRound");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.RoundEvent", b =>
                {
                    b.HasOne("PappaETStats.Server.Domain.MatchRound", "MatchRound")
                        .WithMany("Events")
                        .HasForeignKey("MatchRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchRound");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.Match", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchPlayer", b =>
                {
                    b.Navigation("ClassStats");

                    b.Navigation("WeaponStats");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchRound", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Obituaries");

                    b.Navigation("Sides");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchSeries", b =>
                {
                    b.Navigation("Maps");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchSide", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
