// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PappaETStats.Server.Data;

#nullable disable

namespace PappaETStats.Server.Migrations
{
    [DbContext(typeof(StatsDbContext))]
    partial class StatsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PappaETStats.Server.Domain.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalMatchId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerPort")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalMatchId")
                        .IsUnique();

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchObituary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AttackerGuid")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("AttackerRespawnTime")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MatchRoundId")
                        .HasColumnType("char(36)");

                    b.Property<int>("MeansOfDeath")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetGuid")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("TimestampMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VictimRespawnTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchRoundId");

                    b.ToTable("MatchObituaries");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ClientNum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DamageGiven")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DamageReceived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gibs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatchSideId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rounds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelfKills")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Team")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamDamageGiven")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamDamageReceived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamGibs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamKills")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TimePlayedPercent")
                        .HasColumnType("REAL");

                    b.Property<int>("Xp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchSideId");

                    b.ToTable("MatchPlayers");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchPlayerClassStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MatchPlayerId")
                        .HasColumnType("char(36)");

                    b.Property<long>("Ms")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchPlayerId");

                    b.ToTable("MatchPlayerClassStats");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchPlayerWeaponStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Atts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Deaths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Headshots")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hits")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kills")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MatchPlayerId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Weapon")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchPlayerId");

                    b.ToTable("MatchPlayerWeaponStats");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("DefenderTeam")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IngestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NextTimeLimit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("RoundEndMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RoundEndUnix")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RoundStartMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RoundStartUnix")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeLimit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("WinnerTeam")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "RoundNumber")
                        .IsUnique();

                    b.ToTable("MatchRounds");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchSide", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDefender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MatchRoundId")
                        .HasColumnType("char(36)");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Team")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalDamageGiven")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalDamageReceived")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalGibs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalSelfKills")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalTeamDamageGiven")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalTeamDamageReceived")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalTeamGibs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalTeamKills")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalXp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchRoundId");

                    b.ToTable("MatchSides");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchObituary", b =>
                {
                    b.HasOne("PappaETStats.Server.Domain.MatchRound", "MatchRound")
                        .WithMany("Obituaries")
                        .HasForeignKey("MatchRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchRound");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchPlayer", b =>
                {
                    b.HasOne("PappaETStats.Server.Domain.MatchSide", "MatchSide")
                        .WithMany("Players")
                        .HasForeignKey("MatchSideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchSide");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchPlayerClassStat", b =>
                {
                    b.HasOne("PappaETStats.Server.Domain.MatchPlayer", "MatchPlayer")
                        .WithMany("ClassStats")
                        .HasForeignKey("MatchPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchPlayer");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchPlayerWeaponStat", b =>
                {
                    b.HasOne("PappaETStats.Server.Domain.MatchPlayer", "MatchPlayer")
                        .WithMany("WeaponStats")
                        .HasForeignKey("MatchPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchPlayer");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchRound", b =>
                {
                    b.HasOne("PappaETStats.Server.Domain.Match", "Match")
                        .WithMany("Rounds")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchSide", b =>
                {
                    b.HasOne("PappaETStats.Server.Domain.MatchRound", "MatchRound")
                        .WithMany("Sides")
                        .HasForeignKey("MatchRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchRound");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.Match", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchPlayer", b =>
                {
                    b.Navigation("ClassStats");

                    b.Navigation("WeaponStats");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchRound", b =>
                {
                    b.Navigation("Obituaries");

                    b.Navigation("Sides");
                });

            modelBuilder.Entity("PappaETStats.Server.Domain.MatchSide", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
